repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.6.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
  - repo: https://github.com/DetachHead/basedpyright-pre-commit-mirror
    rev: 1.19.0  # or whatever the latest version is at the time
    hooks:
    - id: basedpyright
